### ISSUE TITLE
Using deadbold from a Maven project

### ISSUE THREAD

**Issue by pycloux** [schaloner/schaloner.github.com#1]
Hello,

I am working on a big project which requires some code to be linked to Deadbolt in a library (a jar) built using Maven.
Please can you tell me what is the right maven dependency XML tag to use ?
I tried some variants of what is in the Build.scala (Ivy I think) but it does not work for maven.

Best regards,

PYC

**Comment by schaloner** [comment]
If you can wait until this evening, I'll release the latest versions into the Maven-style repository.

**Comment by pycloux** [comment]
Hi Steve,

Any news ?

Best regards,

PYC

**Comment by schaloner** [comment]
Hi,

argh, sorry - I completely forgot about this!  I've been swamped recently.
I'll take care of it today - feel free to hurl abuse until it's committed!
- Steve

On Thu, Jun 20, 2013 at 4:04 PM, pycloux notifications@github.com wrote:

> Hi Steve,
> 
> Any news ?
> 
> Best regards,
> 
> PYC
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/schaloner/schaloner.github.com/issues/1#issuecomment-19754779
> .

## 

Steve Chaloner
steve@objectify.be
+32 (0)494 59 13 20

Sharpen your cutting edge...
http://www.objectify.be

**Comment by schaloner** [comment]
OK, you can give this a try.  The artifacts are 
groupId: be.objectify 

artifactId: deadbolt-core
version: 2.1-RC2

artifactId: deadbolt-java
version: 2.1-RC2

artifactId: deadbolt-scala
version: 2.1-RC3

**Comment by pycloux** [comment]
Hi Steve,

Sorry for the delay.

This is working !

Thank you very much.

Will you update it in the future ?

(We’ll add the URL of your repo to our Nexus https://raw.github.com/schaloner/schaloner.github.com/master/maven/releases/).

Best regards,

PYC

---

Pierre-Yves Cloux

**Comment by pycloux** [comment]
Hi Steve,

We tried to connect our Nexus but it seems that it is not working.
We are using the following URL:
https://raw.github.com/schaloner/schaloner.github.com/master/maven/releases/

Is this the right one ?

Best regards,

PYC

**Comment by pycloux** [comment]
Any news ?
