### ISSUE TITLE
Play 2.3.x created module not found in Github

### ISSUE THREAD

**Issue by sivailango** [schaloner/schaloner.github.com#3]
I have created my own module (for couchbase wrapper) followed by the steps mentioned here http://www.objectify.be/wordpress/?p=410. Initially, created the module and tested with local file path and it works. Then i pushed the module to github repository https://github.com/sivailango/sivailango.github.io

In my sample project, tried to load the module from github, my built.sbt is

<pre>
libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  javaWs,
  "com.smartcoders" % "play-java-couchbase_2.11" % "1.0"
)

resolvers += "PlayJavaCouch Wrapper" at "http://sivailango.github.io/releases/"
</pre>

but it couldn't download this dependency, com.smartcoders#play-java-couchbase_2.11;1.0: not found is the error in my console. I have created the github pages using .io domain extension. I couldn't find where was the error? sivailango.github.io is my github page link.

**Comment by schaloner** [comment]
Try this

```
resolvers += Resolver.url("PlayJavaCouch Wrapper", url("http://sivailango.github.io/releases/"))(Resolver.ivyStylePatterns)
```

**Comment by sivailango** [comment]
@schaloner Thanks for your response. It works.
